import { StyleSheet } from 'react-native';

export const SHORTS = [
  {
    id: '1',
    title: 'Factor quick: x^2 + 7x + 10',
    className: 'Algebra 1',
    teacher: 'Ms Vega',
    duration: '00:52',
    views: '1.2k',
    comments: '24',
    note: 'Find two numbers that multiply to 10.',
  },
  {
    id: '2',
    title: 'Reading tone in one paragraph',
    className: 'English 9',
    teacher: 'Mr Chang',
    duration: '01:08',
    views: '860',
    comments: '18',
    note: 'Look for word choice and pacing.',
  },
  {
    id: '3',
    title: 'Newton second law in 60s',
    className: 'Physics',
    teacher: 'Dr Iqbal',
    duration: '00:59',
    views: '2.3k',
    comments: '41',
    note: 'Force equals mass times acceleration.',
  },
];

export const FEEDBACK = [
  {
    id: '1',
    name: 'Avery',
    text: 'Can you show one more example with negatives?',
  },
  {
    id: '2',
    name: 'Jordan',
    text: 'The step with isolating x finally clicked.',
  },
  {
    id: '3',
    name: 'Taylor',
    text: 'Can we get a slower walkthrough on line 3?',
  },
];

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  loadingRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#453D33',
    fontWeight: '600',
  },
  screenRoot: {
    flex: 1,
  },
  safe: {
    flex: 1,
  },
  scroll: {
    padding: 20,
    paddingBottom: 80,
  },
  glowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#FFE3C4',
    opacity: 0.55,
  },
  glowBottom: {
    position: 'absolute',
    bottom: -140,
    left: -100,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#CDEBFF',
    opacity: 0.5,
  },
  header: {
    marginBottom: 24,
    gap: 10,
  },
  brand: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 34,
    color: '#1E1B16',
  },
  tagline: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 15,
    lineHeight: 22,
    color: '#453D33',
  },
  authRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  authPill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: '#1B6E6A',
  },
  authPillText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#FFFFFF',
    fontSize: 12,
  },
  authSwitch: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C1B7AA',
    backgroundColor: '#FFFFFF',
  },
  authSwitchText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 12,
    color: '#453D33',
  },
  section: {
    marginBottom: 26,
  },
  sectionHeader: {
    marginBottom: 14,
    gap: 6,
  },
  sectionTitle: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 20,
    color: '#1E1B16',
  },
  sectionSubtitle: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 14,
    color: '#5B5144',
    marginTop: 6,
    marginBottom: 14,
  },
  cardRow: {
    gap: 14,
  },
  card: {
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
    shadowColor: '#D9CBBE',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 4,
  },
  uploadCard: {
    borderColor: '#FFD6B8',
  },
  draftCard: {
    borderColor: '#D6E6FF',
    marginTop: 14,
  },
  cardEyebrow: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 12,
    color: '#B86B3C',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
  },
  cardTitle: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 18,
    color: '#1E1B16',
    marginTop: 6,
  },
  cardBody: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#5B5144',
    marginVertical: 10,
  },
  primaryButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#FF6B4A',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  primaryButtonText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#FFFFFF',
    fontSize: 13,
  },
  secondaryButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#F4EFE8',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  secondaryButtonText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#453D33',
    fontSize: 13,
  },
  feed: {
    gap: 16,
  },
  shortCard: {
    padding: 16,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
    shadowColor: '#D9CBBE',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 3,
  },
  shortMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  classTag: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#EAF4FF',
  },
  classTagText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 12,
    color: '#1B6E6A',
  },
  duration: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 12,
    color: '#B86B3C',
  },
  preview: {
    height: 160,
    borderRadius: 18,
    overflow: 'hidden',
    justifyContent: 'space-between',
    padding: 14,
  },
  previewBadge: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  previewBadgeText: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 11,
    color: '#1E1B16',
  },
  previewFooter: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(30, 27, 22, 0.75)',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  previewFooterText: {
    fontFamily: 'SpaceGrotesk_400Regular',
    color: '#FFFFFF',
    fontSize: 12,
  },
  shortContent: {
    marginTop: 14,
    gap: 6,
  },
  shortTitle: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 16,
    color: '#1E1B16',
  },
  shortNote: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 13,
    color: '#5B5144',
  },
  shortFooter: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shortTeacher: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 12,
    color: '#1B6E6A',
  },
  shortStats: {
    fontFamily: 'SpaceGrotesk_400Regular',
    fontSize: 12,
    color: '#8B7D6B',
  },
  feedbackCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
    gap: 14,
    shadowColor: '#D9CBBE',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 3,
  },
  feedbackRow: {
    flexDirection: 'row',
    gap: 12,
  },
  feedbackAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFD6B8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackAvatarText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#7D3E1D',
  },
  feedbackBody: {
    flex: 1,
    gap: 4,
  },
  feedbackName: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#1E1B16',
  },
  feedbackText: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    color: '#5B5144',
    fontSize: 13,
    lineHeight: 18,
  },
  footer: {
    padding: 20,
    borderRadius: 22,
    backgroundColor: '#1E1B16',
    gap: 10,
  },
  footerTitle: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 18,
    color: '#FFF6E5',
  },
  footerText: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 13,
    color: '#E7D7C7',
  },
  footerButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  tabBar: {
    borderTopWidth: 0,
    backgroundColor: '#FFFDF9',
    paddingTop: 6,
    height: 62,
  },
  inboxCard: {
    marginTop: 18,
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
    gap: 12,
  },
  inboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inboxTag: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    fontSize: 11,
    color: '#1B6E6A',
    textTransform: 'uppercase',
  },
  inboxText: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 13,
    color: '#5B5144',
  },
  uploadActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  exploreGrid: {
    marginTop: 18,
    gap: 14,
  },
  exploreCard: {
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 18,
  },
  profileAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#1B6E6A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    fontFamily: 'SpaceGrotesk_600SemiBold',
    color: '#FFFFFF',
    fontSize: 20,
  },
  profileName: {
    fontFamily: 'SpaceGrotesk_700Bold',
    fontSize: 18,
    color: '#1E1B16',
  },
  profileRole: {
    fontFamily: 'IBM_Plex_Serif_400Regular',
    fontSize: 13,
    color: '#5B5144',
  },
  profileCard: {
    marginBottom: 14,
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFE7DD',
    gap: 10,
  },
});
